spring.application.name=abysalto-backend-task
dummyjson.base-url=https://dummyjson.com
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=60s
#namjerno ostavljen javan jwt secret
jwt.secret=+oKtk0/yHBu0D1MvJT+aeu8GDpaaquCIBK0bttA2EDh4J0VDqb26CEdHFFAiiI0O
jwt.expiration-ms=3600000
